#!/usr/bin/ruby
# -*- coding:utf-8 -*-
#
# 最も新しいファイルを出力
# Tipsに書く
#

pat = ARGV.shift
exit unless pat

matched = `mdfind -name #{pat}`
exit if matched == ''

puts matched.split(/\n/).sort { |a,b|
  File.mtime(b) <=> File.mtime(a)
}[0]

#  puts "#{File.mtime(file).strftime('%Y%m%d%H%M%S')} #{file}"
